Setup server and make index
Manuel-Antunes/GO-RPG pull request #7
Opened 2021-04-17 17:13 UTC by Manuel-Antunes

sets up all the environment with go, addtional packages and other language featueres
sets up a HTTP server with framework labstack echo and sets the html view engine
creates the index screen with styles and scripts

2021-04-18 15:58 UTC, danielfireman requested changes
Muito bacana a primeira iteração, Manuel!

Além de enderçar os comentários abaixo, por favor, apagar o arquivo go-bin.exe do repositório e atualizar o .gitignore

2021-04-18 15:58 UTC, danielfireman commented on main.go
> +	e.Renderer = t
Declarar e assinalar `t`.

```go
e.Renderer = &Template{
		templates: template.Must(template.ParseGlob("src/views/*.html")),
}
```

2021-04-18 15:58 UTC, danielfireman commented on main.go
> +	return c.Render(http.StatusOK, "index", jorge)
Os dados não são utilizados no template. Favor remover (e remover a classe). Pode adicionar num outro PR.

2021-04-18 15:58 UTC, danielfireman commented on src/public/js/index.js
> +document.getElementById('log-button')
Não seria mais simples utilizar form para fazer a chamada a API?

2021-04-18 21:23 UTC, Manuel-Antunes commented on src/public/js/index.js
> +document.getElementById('log-button')
eu sei, tem até um comentário aí, que eu só coloquei msm pra ter um javascript

2021-04-18 21:23 UTC, Manuel-Antunes commented on main.go
> +	return c.Render(http.StatusOK, "index", jorge)
sim sim, vou remover

2021-04-18 21:24 UTC, Manuel-Antunes commented on main.go
> +	e.Renderer = t
ok!

2021-04-19 00:18 UTC, Manuel-Antunes commented on src/public/js/index.js
> +document.getElementById('log-button')
Professor, eu fiz uma pequena substituição na ideia que foi passada, pq ele pede pra eu fazer um post numa rota, mas eu pensei em fazer melhor, o botão nos leva até uma tela de sign-up, que teria um formulário e um botão de cadastro, e ele faria a chamada api, eai ?

2021-04-19 11:40 UTC, danielfireman commented on src/public/js/index.js
> +document.getElementById('log-button')
Não precisamos de complicação, Manuel. Precisamos apenas que você exercite o mínimo para o papo de logo mais :)

2021-04-19 11:41 UTC, danielfireman approved these changes

2021-04-19 12:18 UTC, merged